Repository ftornberg/Social-Network, pull requests merged in 2022-12, with the labels that each got.

#107 48 skapa flödet för follows
  API/Controllers/FollowerController.cs
  API/Controllers/PostController.cs
  API/Dto/Follower/FollowerDto.cs
  API/Dto/FollowersDto.cs
  API/Helpers/MappingProfile.cs
  Entity/DirectMessage.cs
  Entity/Follower.cs
  Infrastructure/NetworkContext.cs
Labels: enhancement

#108 105 skriv tester för controllers
  Social-Network.Test/UserTests/DirectMessageTest.cs
  Social-Network.Test/UserTests/PostTest.cs
  Social-Network.Test/UserTests/UserTest.cs
Labels: enhancement

#110 109 lägg till name i post
  API/Dto/Follower/FollowerDto.cs
  API/Dto/PostDto.cs
  Entity/Follower.cs
  Entity/Post.cs
  client/src/models/post.ts
Labels: enhancement

#113 106 implementera dm side quest rätt namn på posts i wall
  API/Controllers/DirectMessageController.cs
  API/Controllers/FollowerController.cs
  API/Controllers/PostController.cs
  API/Controllers/UserController.cs
  API/Dto/DirectMessageDto.cs
  API/Dto/PostDto.cs
  API/Dto/UserRegisterDto.cs
  API/Dto/UserUpdateDto.cs
  API/Helpers/MappingProfile.cs
  client/src/App.tsx
  client/src/actions/agent.ts
  client/src/component/Message.tsx
  client/src/component/SendMessage.tsx
  client/src/component/ShowMessages.tsx
  client/src/component/SideBar.tsx
  client/src/component/UserWall.tsx
  client/src/component/Wall.tsx
  client/src/models/directmessage.ts
  client/src/models/followers.tsx
  client/src/pages/HomePage.tsx
Labels: enhancement

#115 Usernames on post, followers and following.. DM to be done.
  API/Controllers/FollowerController.cs
  API/Controllers/PostController.cs
  client/src/actions/agent.ts
  client/src/component/ShowMessages.tsx
  client/src/component/SideBar.tsx
  client/src/component/UserWall.tsx
  client/src/component/Wall.tsx
  client/src/models/followers.ts
Labels: enhancement

#116 FollowerTest
  Social-Network.Test/UserTests/CommentTest.cs
  Social-Network.Test/UserTests/DirectMessageTest.cs
  Social-Network.Test/UserTests/FollowerTest.cs
  Social-Network.Test/UserTests/PostTest.cs
  Social-Network.Test/UserTests/UserTest.cs
Labels: enhancement

#119 114 remove comments space and make props non nullable
  API/Controllers/BaseController.cs
  API/Controllers/CommentController.cs
  API/Controllers/DirectMessageController.cs
  API/Controllers/FollowerController.cs
  API/Controllers/PostController.cs
  API/Controllers/UserController.cs
  API/Dto/Comment/CommentDto.cs
  API/Dto/DirectMessage/DirectMessageDto.cs
  API/Dto/DirectMessageDto.cs
  API/Dto/Follower/FollowerDto.cs
  API/Dto/Post/PostDto.cs
  API/Dto/User/UserCredentialsDto.cs
  API/Dto/User/UserDto.cs
  API/Dto/User/UserRegisterDto.cs
  API/Dto/UserCredentialsDto.cs
  API/Dto/UserRegisterDto.cs
  API/ErrorResponse/ApiException.cs
  API/ErrorResponse/ApiResponse.cs
  API/ErrorResponse/ApiValidationErrorResponse.cs
  API/GlobalUsings.cs
  API/Helpers/MappingProfile.cs
  API/Middleware/ExceptionMiddleware.cs
  API/Program.cs
  Entity/BaseEntity.cs
  Entity/Comment.cs
  Entity/DirectMessage.cs
  Entity/Follower.cs
  Entity/Interfaces/IGenericRepository.cs
  Entity/Post.cs
  Entity/User.cs
  Infrastructure/GenericRepository.cs
  Infrastructure/NetworkContext.cs
  Infrastructure/NetworkContextSeed.cs
  Social-Network.Test/GlobalTestUsings.cs
  Social-Network.Test/UserTests/CommentTest.cs
  Social-Network.Test/UserTests/DirectMessageTest.cs
  Social-Network.Test/UserTests/FollowerTest.cs
  Social-Network.Test/UserTests/PostTest.cs
  Social-Network.Test/UserTests/UserTest.cs
  Social-Network.Test/Usings.cs
  client/package-lock.json
Labels: documentation

#128 127 fixa namespace på dtos
  API/Controllers/CommentController.cs
  API/Controllers/DirectMessageController.cs
  API/Controllers/FollowerController.cs
  API/Controllers/PostController.cs
  API/Controllers/UserController.cs
  API/Dto/Comment/CommentDto.cs
  API/Dto/DirectMessage/DirectMessageDto.cs
  API/Dto/Follower/FollowerDto.cs
  API/Dto/Post/PostDto.cs
  API/Dto/User/UserCredentialsDto.cs
  API/Dto/User/UserDto.cs
  API/Dto/User/UserRegisterDto.cs
  API/GlobalAPIUsings.cs
Labels: bug

#132 Friend component fixed
  client/src/App.tsx
  client/src/component/Conversations.tsx
  client/src/component/FindFriends.tsx
  client/src/component/ShowMessages.tsx
  client/src/component/ShowUsers.tsx
  client/src/component/SideBar.tsx
  client/src/pages/HomePage.tsx
Labels: enhancement

#131 Fixed test names
  API/Controllers/PostController.cs
  Social-Network.Test/UserTests/CommentTest.cs
  Social-Network.Test/UserTests/DirectMessageTest.cs
  Social-Network.Test/UserTests/FollowerTest.cs
  Social-Network.Test/UserTests/PostTest.cs
  Social-Network.Test/UserTests/UserTest.cs
Labels: bug, documentation

#135 126 add api middleware exception handler
  API/Controllers/CommentController.cs
  API/Controllers/DirectMessageController.cs
  API/Controllers/FollowerController.cs
  API/Controllers/PostController.cs
  API/Controllers/UserController.cs
  API/GlobalAPIUsings.cs
  API/Middleware/ExceptionMiddleware.cs
  API/Program.cs
Labels: bug, enhancement

#139 Refactored dtos to simplify/optimize flow of data.
  API/Controllers/DirectMessageController.cs
  API/Controllers/FollowerController.cs
  API/Controllers/PostController.cs
  API/Controllers/UserController.cs
  API/Dto/DirectMessage/DirectMessageAddDto.cs
  API/Dto/DirectMessage/DirectMessageGetDto.cs
  API/Dto/Follower/FollowerAddDto.cs
  API/Dto/Follower/FollowerGetDto.cs
  API/Dto/Post/PostAddDto.cs
  API/Dto/Post/PostGetDto.cs
  API/Dto/User/UserAddDto.cs
  API/Dto/User/UserDto.cs
  API/Dto/User/UserGetDto.cs
  API/Dto/User/UserRegisterDto.cs
  API/Helpers/MappingProfile.cs
  Infrastructure/GenericRepository.cs
  Infrastructure/NetworkContextSeed.cs
Labels: enhancement

#144 Frontend Cleanup, Tests organized
  Social-Network.Test/CommentTests/CommentTest.cs
  Social-Network.Test/DirectMessageTests/DirectMessageTest.cs
  Social-Network.Test/FollowerTests/FollowerTest.cs
  Social-Network.Test/GenericRepositoryTests/AddAsyncTests.cs
  Social-Network.Test/GenericRepositoryTests/GetByIdAsyncTest.cs
  Social-Network.Test/GenericRepositoryTests/ListAllAsyncTest.cs
  Social-Network.Test/PostTests/PostTest.cs
  client/src/App.tsx
  client/src/actions/agent.ts
  client/src/component/Conversations.tsx
  client/src/component/Message.tsx
  client/src/component/RegisterUser.tsx
  client/src/component/SendMessage.tsx
  client/src/component/ShowFollowers.tsx
  client/src/component/ShowMessages.tsx
  client/src/component/ShowUser.tsx
  client/src/component/ShowUsers.tsx
  client/src/component/UserWall.tsx
  client/src/pages/DirectMessagePage.tsx
Labels: documentation
